### ISSUE TITLE
crashes at startup on lineageOS + microG

### ISSUE THREAD

**Issue by krodelabestiole** [sethchhim/Kuboo#51]
I can't launch it.

Version 1.1.5 on LineageOS 15.1 (android 8.1.0) with microG.

Here is the fatal error :
```
FATAL EXCEPTION: main
Process: com.sethchhim.kuboo, PID: 8398
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.sethchhim.kuboo/com.sethchhim.kuboo_client.ui.splash.SplashActivity}: android.content.res.Resources$NotFoundException: Drawable com.sethchhim.kuboo:drawable/app_splash_background with resource ID #0x7f08005f
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
at android.app.ActivityThread.-wrap11(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6494)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)
Caused by: android.content.res.Resources$NotFoundException: Drawable com.sethchhim.kuboo:drawable/app_splash_background with resource ID #0x7f08005f
Caused by: android.content.res.Resources$NotFoundException: File res/drawable/app_splash_background.xml from drawable resource ID #0x7f08005f
at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:820)
at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:630)
at android.content.res.Resources.getDrawableForDensity(Resources.java:877)
at android.content.res.XResources.getDrawableForDensity(XResources.java:868)
at android.content.res.Resources.getDrawable(Resources.java:819)
at android.content.res.XResources.getDrawable(XResources.java:790)
at android.content.Context.getDrawable(Context.java:605)
at android.support.v4.a.a.a(Unknown Source:6)
at android.support.v7.widget.AppCompatDrawableManager.getDrawable(Unknown Source:16)
at android.support.v7.widget.TintTypedArray.getDrawableIfKnown(Unknown Source:24)
at android.support.v7.app.f.<init>(Unknown Source:63)
at android.support.v7.app.e.a(Unknown Source:6)
at android.support.v7.app.c.l(Unknown Source:4)
at android.support.v7.app.c.onCreate(Unknown Source:0)
at a.a.a.b.onCreate(Unknown Source:3)
at com.sethchhim.kuboo_client.ui.a.a.onCreate(Unknown Source:0)
at com.sethchhim.kuboo_client.ui.splash.SplashActivity.onCreate(Unknown Source:0)
at android.app.Activity.performCreate(Activity.java:6999)
at android.app.Activity.performCreate(Activity.java:6990)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
at android.app.ActivityThread.-wrap11(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6494)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)
Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x7f08005e
at android.content.res.ResourcesImpl.getValueForDensity(ResourcesImpl.java:224)
at android.content.res.Resources.getValueForDensity(Resources.java:1334)
at android.graphics.drawable.BitmapDrawable.updateStateFromTypedArray(BitmapDrawable.java:798)
at android.graphics.drawable.BitmapDrawable.inflate(BitmapDrawable.java:754)
at android.graphics.drawable.DrawableInflater.inflateFromXmlForDensity(DrawableInflater.java:142)
at android.graphics.drawable.Drawable.createFromXmlInnerForDensity(Drawable.java:1295)
```

Thanks for any help !

**Comment by sethchhim** [comment]
Is this a debug build through android studio? I have had some issues like this in the past but it was the IDE's fault. Sometimes I had to invalidate caches + rebuild to reset everything correctly. Let me know what IDE you are using and version.

**Comment by krodelabestiole** [comment]
no IDE, no debug, it's the logcat output.

I've just installed the standard stable binary version I've got from yalp (which is basically just an anonymous proxy for the play store).

**Comment by sethchhim** [comment]
I can't offer support for outside vendors because I don't know what they do to the package.

You can try these options which are confirmed to work:
- install from play store
- build from scratch and install
- download apk from "Releases" section (1.1.5) and install

**Comment by krodelabestiole** [comment]
it's the exact same apk, it is provided by the play store. only the downloading tools changes.
it's a different downloading tool, the "repository" stays the same : google.

Before the fatal error I had a warning like so if that can be of any help :
```
Token{c666192 ActivityRecord{aef2b1d u0 com.sethchhim.kuboo/com.sethchhim.kuboo_client.ui.splash.SplashActivity t7182}} failed creating starting window
android.content.res.Resources$NotFoundException: Drawable com.sethchhim.kuboo:drawable/app_splash_background with resource ID #0x7f08005f
Caused by: android.content.res.Resources$NotFoundException: File res/drawable/app_splash_background.xml from drawable resource ID #0x7f08005f
at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:820)
at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:630)
at android.content.res.Resources.getDrawableForDensity(Resources.java:877)
at android.content.res.XResources.getDrawableForDensity(XResources.java:868)
at android.content.res.Resources.getDrawable(Resources.java:819)
at android.content.res.XResources.getDrawable(XResources.java:790)
at android.content.Context.getDrawable(Context.java:605)
at com.android.server.policy.PhoneWindowManager.addSplashScreen(PhoneWindowManager.java:3291)
at com.android.server.wm.SplashScreenStartingData.createStartingSurface(SplashScreenStartingData.java:55)
at com.android.server.wm.AppWindowContainerController.lambda$-com_android_server_wm_AppWindowContainerController_4735(AppWindowContainerController.java:145)
at com.android.server.wm.-$Lambda$aEpJ2RCAIjecjyIIYTv6ricEwh4.$m$4(Unknown Source:4)
at com.android.server.wm.-$Lambda$aEpJ2RCAIjecjyIIYTv6ricEwh4.run(Unknown Source:27)
at android.os.Handler.handleCallback(Handler.java:790)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:164)
at android.os.HandlerThread.run(HandlerThread.java:65)
at com.android.server.ServiceThread.run(ServiceThread.java:46)
Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x7f08005e
at android.content.res.ResourcesImpl.getValueForDensity(ResourcesImpl.java:224)
at android.content.res.Resources.getValueForDensity(Resources.java:1334)
at android.graphics.drawable.BitmapDrawable.updateStateFromTypedArray(BitmapDrawable.java:798)
at android.graphics.drawable.BitmapDrawable.inflate(BitmapDrawable.java:754)
at android.graphics.drawable.DrawableInflater.inflateFromXmlForDensity(DrawableInflater.java:142)
at android.graphics.drawable.Drawable.createFromXmlInnerForDensity(Drawable.java:1295)
at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:1284)
at android.graphics.drawable.LayerDrawable.inflateLayers(LayerDrawable.java:279)
at android.graphics.drawable.LayerDrawable.inflate(LayerDrawable.java:194)
at android.graphics.drawable.DrawableInflater.inflateFromXmlForDensity(DrawableInflater.java:142)
at android.graphics.drawable.Drawable.createFromXmlInnerForDensity(Drawable.java:1295)
at android.graphics.drawable.Drawable.createFromXmlForDensity(Drawable.java:1254)
at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:807)
... 16 more
```

**Comment by sethchhim** [comment]
Can you email me the apk and I will test on a sandboxed emulator, just to cover our tracks. sethchhim@gmail.com

**Comment by sethchhim** [comment]
I found a [LineageOS bug](https://review.lineageos.org/c/LineageOS/android_frameworks_base/+/224616/9) for resource loading. Asset Manager was refactored and a small version window where it would crash.

The commit shows it was fixed in `LineageOS 16.0`. Unfortunately I do not have a device to test this operating system but I can advise you upgrade to sort this out. Good luck, hope this helps.

**Comment by krodelabestiole** [comment]
I've just download the latest release from this github repo and it seems to work. Except it seems to be a "debug version".
I'm sorry I really don't want to install the play store, but since yalp doesn't even have its own repo, there is no way it changes anything.
Thank you very much for the fast and good help anyway, much appreciated.

I will stick to the debug version for now.

**Comment by sethchhim** [comment]
I understand your concern. I'm also building an open source, zero knowledge server and it is coming along nicely. Keep an eye out.

**Comment by sethchhim** [comment]
@krodelabestiole I will start to upload both debug and release apk's. This is a courtesy message to let you know 1.1.8 is available in the releases section.
