### ISSUE TITLE
Kuboo Server Alpha 0.0.1

### ISSUE THREAD

**Issue by sethchhim** [sethchhim/Kuboo#54]
Here is my server project I'm working on if you want to check it out. You can download it in the [releases](https://github.com/sethchhim/Kuboo/releases) section (kuboo-0.0.1-ALPHA.jar).

Installation:
`java -jar kuboo-0.0.1-ALPHA.jar`

Authentication:
```
Login username[1] password[1] admin[true]
Login username[2] password[2] admin[false]
Login username[3] password[3] admin[false]
Login username[4] password[4] admin[false]
Login username[5] password[5] admin[false]
Login username[6] password[6] admin[false]
```

Populate sources:
`Navigation Menu -> Admin -> Edit Sources`

Port: 8080
Example: http://192.168.1.100:8080/

This is pre-release software intended for testing purposes only. No feedback or feature requests will be taken at this time.

**Comment by cesalo** [comment]
I know you said that no feedback is needed but tried to install it and threw out this error - Any preparation needed?:

2019-01-03 22:33:52.653 [main] INFO  Application - No ktor.deployment.watch patterns match classpath entries, automatic reload is not active
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:71)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Static.call(CallerImpl.kt:80)
        at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:106)
        at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflect_api(KCallableImpl.kt:152)
        at kotlin.reflect.jvm.internal.KCallableImpl.callBy(KCallableImpl.kt:110)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.callFunctionWithInjection(ApplicationEngineEnvironmentReloading.kt:347)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.executeModuleFunction(ApplicationEngineEnvironmentReloading.kt:297)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.instantiateAndConfigureApplication(ApplicationEngineEnvironmentReloading.kt:273)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.createApplication(ApplicationEngineEnvironmentReloading.kt:126)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.start(ApplicationEngineEnvironmentReloading.kt:245)
        at io.ktor.server.netty.NettyApplicationEngine.start(NettyApplicationEngine.kt:106)
        at io.ktor.server.netty.NettyApplicationEngine.start(NettyApplicationEngine.kt:18)
        at io.ktor.server.engine.ApplicationEngine$DefaultImpls.start$default(ApplicationEngine.kt:46)
        at io.ktor.server.netty.EngineMain.main(EngineMain.kt:17)
Caused by: java.io.FileNotFoundException: \\/home/xxxxx/Kuboo-Server\keys\kuboo.jks (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at MainKt.toKeyStore(Main.kt:55)
        at MainKt.access$toKeyStore(Main.kt:1)
        at MainKt$getEnvironment$1.invoke(Main.kt:35)
        at MainKt$getEnvironment$1.invoke(Main.kt)
        at io.ktor.server.engine.ApplicationEngineEnvironmentBuilder.build(ApplicationEngineEnvironment.kt:95)
        at io.ktor.server.engine.ApplicationEngineEnvironmentKt.applicationEngineEnvironment(ApplicationEngineEnvironment.kt:40)
        at MainKt.getEnvironment(Main.kt:29)
        at MainKt.main(Main.kt:26)
        ... 18 more

**Comment by sethchhim** [comment]
`Caused by: java.io.FileNotFoundException: \\/home/xxxxx/Kuboo-Server\keys\kuboo.jks (No such file or directory)`

Are you trying to install from a network source? I haven't tested that yet.

**Comment by sethchhim** [comment]
This is a bad idea to release unfinished broken software. I will just post some screenshots or gifs later.
